### ISSUE TITLE
cut off dates not clear in "selection process" section

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#437] opened 2017-06-21 21:58 UTC
![image](https://user-images.githubusercontent.com/15656538/27408537-1a8edf44-56d5-11e7-9a4b-8b06fcf08c8b.png)

**Comment by rebeccaradding** [comment] 2017-06-22 16:28
@jsms90 thanks for raising this issue. We probably need to state a clear closing date for London - July 31 is fine with me - thoughts from others?

**Comment by BartBucknill** [comment] 2017-07-01 14:00
@rebeccaradding I received a query from a potential applicant about this yesterday. It would be great to get the site updated with the correct date ASAP, as we are now already in July. Have we confirmed that the London cutoff date is July 31st?

**Comment by rebeccaradding** [comment] 2017-07-01 14:08
@BartBucknill there is an open PR, feel free to review it so it can more quickly be merged.

**Comment by jsms90** [comment] 2017-07-01 20:08
@rebeccaradding I don't think the current PR addresses the need for an actual cut off date to be set?

**Comment by BartBucknill** [comment] 2017-07-01 21:15
@rebeccaradding @jsms90 I also don't see a current PR addressing this issue; in [our-site pull requests](https://github.com/foundersandcoders/our-site/pulls) I see two PRs both of which are fixing formatting issues. I'll happily make a pull request to insert text stating the cutoff date if we can confirm what that date is.

**Comment by jsms90** [comment] 2017-07-01 21:38
@BartBucknill Sorry. I just merged it - https://github.com/foundersandcoders/our-site/pull/445

**Comment by BartBucknill** [comment] 2017-07-01 22:11
@jsms90 thanks! The text strongly implies that July 31st is the cut off date, but still falls short of actually stating it clearly and unequivocally; it leaves open the possibility that the cut off date for next cohort applications could in fact be earlier. Applicants need not delay in submitting the form and this is stated clearly, but I'm sure they will appreciate having a firm date after which (and not before) applications will be reviewed. This would serve as a goal before which they can aim to complete the prerequisites. I know that for me having a clear date was certainly something I appreciated.
*If* July 31st is the date for this it would be simple to clarify things further by changing:
> We will review applications and offer interviews at the end of July

to:
> From 31st July we will review applications and offer interviews

**Comment by rebeccaradding** [comment] 2017-07-02 04:08
@BartBucknill since @jsms90 has already merged the first one, why don't you go ahead and create another?

**Closed** 2017-08-29 11:10 UTC
